package hybridcraft;

import hybridcraft.IngotStuff.combiner.GuiHandler;
import net.minecraft.src.EnumArmorMaterial;
import net.minecraft.src.EnumToolMaterial;
import net.minecraftforge.common.Configuration;
import net.minecraftforge.common.EnumHelper;
import cpw.mods.fml.common.Mod.PreInit;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;

public class Config {

	// added new categories
	public static final String CATEGORY_TOOL = "tools";
	public static final String CATEGORY_INGOT = "ingots";
	public static final String CATEGORY_ARMOR = "armors";
	public static final String CATEGORY_FLOWER = "flowers";

	public static int  dirtswordID;
	public static int  dirtpickID;
	public static int  dirtaxeID;
	public static int  dirtshovelID;
	public static int  dirthoeID;
	public static int  dirtoneswordID;
	public static int  dirtonepickID;
	public static int  dirtoneaxeID;
	public static int  dirtoneshovelID;
	public static int  dirtonehoeID;
	public static int  dironswordID;
	public static int  dironpickID;
	public static int  dironaxeID;
	public static int  dironshovelID;
	public static int  dironhoeID;
	public static int  diroldswordID;
	public static int  diroldpickID;
	public static int  diroldaxeID;
	public static int  diroldshovelID;
	public static int  diroldhoeID;
	public static int  dirmendswordID;
	public static int  dirmendpickID;
	public static int  dirmendaxeID;
	public static int  dirmendshovelID;
	public static int  dirmendhoeID;
	public static int  stornswordID;
	public static int  stornpickID;
	public static int  stornaxeID;
	public static int  stornshovelID;
	public static int  stornhoeID;
	public static int  stoldswordID;
	public static int  stoldpickID;
	public static int  stoldaxeID;
	public static int  stoldshovelID;
	public static int  stoldhoeID;
	public static int  stomendswordID;
	public static int  stomendpickID;
	public static int  stomendaxeID;
	public static int  stomendshovelID;
	public static int  stomendhoeID;
	public static int  iroldswordID;
	public static int  iroldpickID;
	public static int  iroldaxeID;
	public static int  iroldshovelID;
	public static int  iroldhoeID;
	public static int  irmendswordID;
	public static int  irmendpickID;
	public static int  irmendaxeID;
	public static int  irmendshovelID;
	public static int  irmendhoeID;
	public static int  gomendswordID;
	public static int  gomendpickID;
	public static int  gomendaxeID;
	public static int  gomendshovelID;
	public static int  gomendhoeID;
	public static int  obsidianswordID;
	public static int  obsidianpickID;
	public static int  obsidianaxeID;
	public static int  obsidianshovelID;
	public static int  obsidianhoeID;
	public static int  dirtHelmetID;
	public static int  dirtPlateID;
	public static int  dirtLegsID;
	public static int  dirtBootsID;
	public static int  dirtoneHelmetID;
	public static int  dirtonePlateID;
	public static int  dirtoneLegsID;
	public static int  dirtoneBootsID;
	public static int  dironHelmetID;
	public static int  dironPlateID;
	public static int  dironLegsID;
	public static int  dironBootsID;
	public static int  diroldHelmetID;
	public static int  diroldPlateID;
	public static int  diroldLegsID;
	public static int  diroldBootsID;
	public static int  dirmendHelmetID;
	public static int  dirmendPlateID;
	public static int  dirmendLegsID;
	public static int  dirmendBootsID;
	public static int  stornHelmetID;
	public static int  stornPlateID;
	public static int  stornLegsID;
	public static int  stornBootsID;
	public static int  stoldHelmetID;
	public static int  stoldPlateID;
	public static int  stoldLegsID;
	public static int  stoldBootsID;
	public static int  stomendHelmetID;
	public static int  stomendPlateID;
	public static int  stomendLegsID;
	public static int  stomendBootsID;
	public static int  iroldHelmetID;
	public static int  iroldPlateID;
	public static int  iroldLegsID;
	public static int  iroldBootsID;
	public static int  irmendHelmetID;
	public static int  irmendPlateID;
	public static int  irmendLegsID;
	public static int  irmendBootsID;
	public static int  gomendHelmetID;
	public static int  gomendPlateID;
	public static int  gomendLegsID;
	public static int  gomendBootsID;
	public static int  obsidianHelmetID;
	public static int  obsidianPlateID;
	public static int  obsidianLegsID;
	public static int  obsidianBootsID;
	public static int  dirtBlockID;
	public static int  dirtoneBlockID;
	public static int  dironBlockID;
	public static int  diroldBlockID;
	public static int  dirmendBlockID;
	public static int  stoneBlockID;
	public static int  stornBlockID;
	public static int  stoldBlockID;
	public static int  stomendBlockID;
	public static int  iroldBlockID;
	public static int  irmendBlockID;
	public static int  gomendBlockID;
	public static int  dandID;
	public static int  davelID;
	public static int  doneID;
	public static int  dirtFlowerID;
	public static int  stoneFlowerID;
	public static int  ironFlowerID;
	public static int  goldFlowerID;
	public static int  diamondFlowerID;
	public static int  obsidianFlowerID;
	public static int  sandBlockID;
	public static int  stoneHelmetID;
	public static int  stonePlateID;
	public static int  stoneLegsID;
	public static int  stoneBootsID;
	public static int  sandHelmetID;
	public static int  sandPlateID;
	public static int  sandLegsID;
	public static int  sandBootsID;
	public static int  sandswordID;
	public static int  sandpickID;
	public static int  sandaxeID;
	public static int  sandshovelID;
	public static int  sandhoeID;
	public static int  cobbleswordID;
	public static int  cobblepickID;
	public static int  cobbleaxeID;
	public static int  cobbleshovelID;
	public static int  cobblehoeID;
	public static int  emeraldswordID;
	public static int  emeraldpickID;
	public static int  emeraldaxeID;
	public static int  emeraldshovelID;
	public static int  emeraldhoeID;
	public static int  emeraldflowerID;
	public static int  emeraldhelmetID;
	public static int  emeraldplateID;
	public static int  emeraldlegsID;
	public static int  emeraldbootsID;
	public static int  combinerID;
	public static int  obsidianShardID;
	public static int  obsidianIngotID;
	public static int  sandIngotID;
	public static int  dirtIngotID;

	@PreInit
	public void preload(FMLPreInitializationEvent event) {
		
		// configure item numbers
		Configuration config = new Configuration(
				event.getSuggestedConfigurationFile());

		obsidianShardID = config.get(CATEGORY_INGOT, "Obsidian Shard", 572).getInt();
		obsidianIngotID = config.get(CATEGORY_INGOT, "Obsidian Ingot", 573).getInt();
		sandIngotID = config.get(CATEGORY_INGOT, "Sand Ingot", 642).getInt();
		dirtIngotID = config.get(CATEGORY_INGOT, "Dirt Ingot", 560).getInt();
		dirtswordID = config.get(CATEGORY_TOOL, "Dirt Sword", 500).getInt();
		dirtpickID = config.get(CATEGORY_TOOL, "Dirt Pickaxe", 501).getInt();
		dirtaxeID = config.get(CATEGORY_TOOL, "Dirt Axe", 502).getInt();
		dirtshovelID = config.get(CATEGORY_TOOL, "Dirt Shovel", 503).getInt();
		dirthoeID = config.get(CATEGORY_TOOL, "Dirt Hoe", 504).getInt();
		dirtoneswordID = config.get(CATEGORY_TOOL, "Dirtone Sword", 505).getInt();
		dirtonepickID = config.get(CATEGORY_TOOL, "Dirtone Pickaxe", 506).getInt();
		dirtoneaxeID = config.get(CATEGORY_TOOL, "Dirtone Axe", 507).getInt();
		dirtoneshovelID = config.get(CATEGORY_TOOL, "Dirtone Shovel", 508).getInt();
		dirtonehoeID = config.get(CATEGORY_TOOL, "Dirtone Hoe", 509).getInt();
		dironswordID = config.get(CATEGORY_TOOL, "Diron Sword", 510).getInt();
		dironpickID = config.get(CATEGORY_TOOL, "Diron Pickaxe", 511).getInt();
		dironaxeID = config.get(CATEGORY_TOOL, "Diron Axe", 512).getInt();
		dironshovelID = config.get(CATEGORY_TOOL, "Diron Shovel", 513).getInt();
		dironhoeID = config.get(CATEGORY_TOOL, "Diron Hoe", 514).getInt();
		diroldswordID = config.get(CATEGORY_TOOL, "Dirold Sword", 515).getInt();
		diroldpickID = config.get(CATEGORY_TOOL, "Dirold Pickaxe", 516).getInt();
		diroldaxeID = config.get(CATEGORY_TOOL, "Dirold Axe", 517).getInt();
		diroldshovelID = config.get(CATEGORY_TOOL, "Dirold Shovel", 518).getInt();
		diroldhoeID = config.get(CATEGORY_TOOL, "Dirold Hoe", 519).getInt();
		dirmendswordID = config.get(CATEGORY_TOOL, "Dirmend Sword", 520).getInt();
		dirmendpickID = config.get(CATEGORY_TOOL, "Dirmend Pickaxe", 521).getInt();
		dirmendaxeID = config.get(CATEGORY_TOOL, "Dirmend Axe", 522).getInt();
		dirmendshovelID = config.get(CATEGORY_TOOL, "Dirmend Shovel", 523).getInt();
		dirmendhoeID = config.get(CATEGORY_TOOL, "Dirmend Hoe", 524).getInt();
		stornswordID = config.get(CATEGORY_TOOL, "Storn Sword", 525).getInt();
		stornpickID = config.get(CATEGORY_TOOL, "Storn Pick", 526).getInt();
		stornaxeID = config.get(CATEGORY_TOOL, "Storn Axe", 527).getInt();
		stornshovelID = config.get(CATEGORY_TOOL, "Storn Shovel", 528).getInt();
		stornhoeID = config.get(CATEGORY_TOOL, "Storn Hoe", 529).getInt();
		stoldswordID = config.get(CATEGORY_TOOL, "Stold Sword", 530).getInt();
		stoldpickID = config.get(CATEGORY_TOOL, "Stold Pickaxe", 531).getInt();
		stoldaxeID = config.get(CATEGORY_TOOL, "Stold Axe", 532).getInt();
		stoldshovelID = config.get(CATEGORY_TOOL, "Stold Shovel", 533).getInt();
		stoldhoeID = config.get(CATEGORY_TOOL, "Stold Hoe", 534).getInt();
		stomendswordID = config.get(CATEGORY_TOOL, "Stomend Sword", 535).getInt();
		stomendpickID = config.get(CATEGORY_TOOL, "Stomend Pickaxe", 536).getInt();
		stomendaxeID = config.get(CATEGORY_TOOL, "Stomend Axe", 537).getInt();
		stomendshovelID = config.get(CATEGORY_TOOL, "Stomend Shovel", 538).getInt();
		stomendhoeID = config.get(CATEGORY_TOOL, "Stomend Hoe", 539).getInt();
		iroldswordID = config.get(CATEGORY_TOOL, "Irold Sword", 540).getInt();
		iroldpickID = config.get(CATEGORY_TOOL, "Irold Pickaxe", 541).getInt();
		iroldaxeID = config.get(CATEGORY_TOOL, "Irold Axe", 542).getInt();
		iroldshovelID = config.get(CATEGORY_TOOL, "Irold Shovel", 543).getInt();
		iroldhoeID = config.get(CATEGORY_TOOL, "Irold Hoe", 544).getInt();
		irmendswordID = config.get(CATEGORY_TOOL, "Irmend Sword", 545).getInt();
		irmendpickID = config.get(CATEGORY_TOOL, "Irmend Pick", 546).getInt();
		irmendaxeID = config.get(CATEGORY_TOOL, "Irmend Axe", 547).getInt();
		irmendshovelID = config.get(CATEGORY_TOOL, "Irmend Shovel", 548).getInt();
		irmendhoeID = config.get(CATEGORY_TOOL, "Irmend Hoe", 549).getInt();
		gomendswordID = config.get(CATEGORY_TOOL, "Gomend Sword", 550).getInt();
		gomendpickID = config.get(CATEGORY_TOOL, "Gomend Pickaxe", 551).getInt();
		gomendaxeID = config.get(CATEGORY_TOOL, "Gomend Axe", 552).getInt();
		gomendshovelID = config.get(CATEGORY_TOOL, "Gomend Shovel", 553).getInt();
		gomendhoeID = config.get(CATEGORY_TOOL, "Gomend Hoe", 554).getInt();
		obsidianswordID = config.get(CATEGORY_TOOL, "Obsidian Sword", 555).getInt();
		obsidianpickID = config.get(CATEGORY_TOOL, "Obsidian Pickaxe", 556).getInt();
		obsidianaxeID = config.get(CATEGORY_TOOL, "Obsidian Axe", 557).getInt();
		obsidianshovelID = config.get(CATEGORY_TOOL, "Obsidian Shovel", 558).getInt();
		obsidianhoeID = config.get(CATEGORY_TOOL, "Obsidian Hoe", 559).getInt();
		dirtHelmetID = config.get(CATEGORY_ARMOR, "Dirt Helmet ", 574).getInt();
		dirtPlateID = config.get(CATEGORY_ARMOR, "Dirt Chestplate", 575).getInt();
		dirtLegsID = config.get(CATEGORY_ARMOR, "Dirt Leggings", 576).getInt();
		dirtBootsID = config.get(CATEGORY_ARMOR, "Dirt Boots", 577).getInt();
		dirtoneHelmetID = config.get(CATEGORY_ARMOR, "Dirtone Helmet", 578).getInt();
		dirtonePlateID = config.get(CATEGORY_ARMOR, "Dirtone Chestplate", 579).getInt();
		dirtoneLegsID = config.get(CATEGORY_ARMOR, "Dirtone Leggings", 580).getInt();
		dirtoneBootsID = config.get(CATEGORY_ARMOR, "Dirtone Boots", 581).getInt();
		dironHelmetID = config.get(CATEGORY_ARMOR, "Diron Helmet", 582).getInt();
		dironPlateID = config.get(CATEGORY_ARMOR, "Diron Chestplate", 583).getInt();
		dironLegsID = config.get(CATEGORY_ARMOR, "Diron Leggings", 584).getInt();
		dironBootsID = config.get(CATEGORY_ARMOR, "Diron Boots", 585).getInt();
		diroldHelmetID = config.get(CATEGORY_ARMOR, "Dirold Helmet", 586).getInt();
		diroldPlateID = config.get(CATEGORY_ARMOR, "Dirold Chestplate", 587).getInt();
		diroldLegsID = config.get(CATEGORY_ARMOR, "Dirold Leggings", 588).getInt();
		diroldBootsID = config.get(CATEGORY_ARMOR, "Dirold Boots", 589).getInt();
		dirmendHelmetID = config.get(CATEGORY_ARMOR, "Dirmend Helmet", 590).getInt();
		dirmendPlateID = config.get(CATEGORY_ARMOR, "Dirmend Chestplate", 591).getInt();
		dirmendLegsID = config.get(CATEGORY_ARMOR, "Dirmend Leggings", 592).getInt();
		dirmendBootsID = config.get(CATEGORY_ARMOR, "Dirmend Boots", 593).getInt();
		stornHelmetID = config.get(CATEGORY_ARMOR, "Storn Helmet", 594).getInt();
		stornPlateID = config.get(CATEGORY_ARMOR, "Storn Chestplate", 595).getInt();
		stornLegsID = config.get(CATEGORY_ARMOR, "Storn Leggings", 596).getInt();
		stornBootsID = config.get(CATEGORY_ARMOR, "Storn Boots", 597).getInt();
		stoldHelmetID = config.get(CATEGORY_ARMOR, "Stold Helmet", 598).getInt();
		stoldPlateID = config.get(CATEGORY_ARMOR, "Stold Chestplate", 599).getInt();
		stoldLegsID = config.get(CATEGORY_ARMOR, "Stold Leggings", 600).getInt();
		stoldBootsID = config.get(CATEGORY_ARMOR, "Stold Boots", 601).getInt();
		stomendHelmetID = config.get(CATEGORY_ARMOR, "Stomend Helmet", 602).getInt();
		stomendPlateID = config.get(CATEGORY_ARMOR, "Stomend Chestplate", 603).getInt();
		stomendLegsID = config.get(CATEGORY_ARMOR, "Stomend Leggings", 604).getInt();
		stomendBootsID = config.get(CATEGORY_ARMOR, "Stomend Boots", 605).getInt();
		iroldHelmetID = config.get(CATEGORY_ARMOR, "Irold Helmet", 606).getInt();
		iroldPlateID = config.get(CATEGORY_ARMOR, "Irold Chestplate", 607).getInt();
		iroldLegsID = config.get(CATEGORY_ARMOR, "Irold Leggings", 608).getInt();
		iroldBootsID = config.get(CATEGORY_ARMOR, "Irold Boots", 609).getInt();
		irmendHelmetID = config.get(CATEGORY_ARMOR, "Irmend Helmet", 610).getInt();
		irmendPlateID = config.get(CATEGORY_ARMOR, "Irmend Chestplate", 611).getInt();
		irmendLegsID = config.get(CATEGORY_ARMOR, "Irmend Leggings", 612).getInt();
		irmendBootsID = config.get(CATEGORY_ARMOR, "Irmend Boots", 613).getInt();
		gomendHelmetID = config.get(CATEGORY_ARMOR, "Gomend Helmet", 614).getInt();
		gomendPlateID = config.get(CATEGORY_ARMOR, "Gomend Chestplate", 615).getInt();
		gomendLegsID = config.get(CATEGORY_ARMOR, "Gomend Leggings", 616).getInt();
		gomendBootsID = config.get(CATEGORY_ARMOR, "Gomend Boots", 617).getInt();
		obsidianHelmetID = config.get(CATEGORY_ARMOR, "Obsidian Helmet", 618).getInt();
		obsidianPlateID = config.get(CATEGORY_ARMOR, "Obsidian Chestplate", 619).getInt();
		obsidianLegsID = config.get(CATEGORY_ARMOR, "Obsidian Leggings", 620).getInt();
		obsidianBootsID = config.get(CATEGORY_ARMOR, "Obsidian Boots", 621).getInt();
		dirtBlockID = config.get(Configuration.CATEGORY_BLOCK, "Dirt Ingot Block", 622).getInt();
		dirtoneBlockID = config.get(Configuration.CATEGORY_BLOCK, "Dirtone Ingot Block", 623).getInt();
		dironBlockID = config.get(Configuration.CATEGORY_BLOCK, "Diron Ingot Block", 624).getInt();
		diroldBlockID = config.get(Configuration.CATEGORY_BLOCK, "Dirold Ingot Block", 625).getInt();
		dirmendBlockID = config.get(Configuration.CATEGORY_BLOCK, "Dirmend Ingot Block", 626).getInt();
		stoneBlockID = config.get(Configuration.CATEGORY_BLOCK,	"Stone Ingot Block", 627).getInt();
		stornBlockID = config.get(Configuration.CATEGORY_BLOCK,	"Storn Ingot Block", 628).getInt();
		stoldBlockID = config.get(Configuration.CATEGORY_BLOCK,	"Stold Ingot Block", 629).getInt();
		stomendBlockID = config.get(Configuration.CATEGORY_BLOCK, "Stomend Ingot Block", 630).getInt();
		iroldBlockID = config.get(Configuration.CATEGORY_BLOCK,	"Irold Ingot Block", 631).getInt();
		irmendBlockID = config.get(Configuration.CATEGORY_BLOCK, "Irmend Ingot Block", 632).getInt();
		gomendBlockID = config.get(Configuration.CATEGORY_BLOCK, "Gomend Ingot Block", 633).getInt();
		dandID = config.get(Configuration.CATEGORY_BLOCK, "Dirt/Sand Block", 634).getInt();
		davelID = config.get(Configuration.CATEGORY_BLOCK, "Dirt/Gravel Block",	635).getInt();
		doneID = config.get(Configuration.CATEGORY_BLOCK, "Dirt/Stone Block", 636).getInt();
		dirtFlowerID = config.get(CATEGORY_FLOWER, "Dirt Flower", 637).getInt();
		stoneFlowerID = config.get(CATEGORY_FLOWER, "Stone Flower", 638).getInt();
		ironFlowerID = config.get(CATEGORY_FLOWER, "Iron Flower", 639).getInt();
		goldFlowerID = config.get(CATEGORY_FLOWER, "Gold Flower", 640).getInt();
		diamondFlowerID = config.get(CATEGORY_FLOWER, "Diamond Flower", 641).getInt();
		sandBlockID = config.get(Configuration.CATEGORY_BLOCK, "Sand Ingot Block", 643).getInt();
		stoneHelmetID = config.get(CATEGORY_ARMOR, "Stone Helmet", 644).getInt();
		stonePlateID = config.get(CATEGORY_ARMOR, "Stone Chestplate", 645).getInt();
		stoneLegsID = config.get(CATEGORY_ARMOR, "Stone Leggings", 646).getInt();
		stoneBootsID = config.get(CATEGORY_ARMOR, "Stone Boots", 647).getInt();
		sandHelmetID = config.get(CATEGORY_ARMOR, "Sand Helmet", 648).getInt();
		sandPlateID = config.get(CATEGORY_ARMOR, "Sand Chestplate", 649).getInt();
		sandLegsID = config.get(CATEGORY_ARMOR, "Sand Leggings", 650).getInt();
		sandBootsID = config.get(CATEGORY_ARMOR, "Sand Boots", 651).getInt();
		sandswordID = config.get(CATEGORY_TOOL, "Sand Sword", 652).getInt();
		sandpickID = config.get(CATEGORY_TOOL, "Sand Pickaxe", 653).getInt();
		sandaxeID = config.get(CATEGORY_TOOL, "Sand Axe", 654).getInt();
		sandshovelID = config.get(CATEGORY_TOOL, "Sand Shovel", 655).getInt();
		sandhoeID = config.get(CATEGORY_TOOL, "Sand Hoe", 656).getInt();
		cobbleswordID = config.get(CATEGORY_TOOL, "Cobble Sword", 657).getInt();
		cobblepickID = config.get(CATEGORY_TOOL, "Cobble Pickaxe", 658).getInt();
		cobbleaxeID = config.get(CATEGORY_TOOL, "Cobble Axe", 659).getInt();
		cobbleshovelID = config.get(CATEGORY_TOOL, "Cobble Shovel", 660).getInt();
		cobblehoeID = config.get(CATEGORY_TOOL, "Cobble Hoe", 661).getInt();
		obsidianFlowerID = config.get(CATEGORY_FLOWER, "Obsidian Flower", 666).getInt();
		emeraldswordID = config.get(CATEGORY_TOOL, "Emerald Sword", 667).getInt();
		emeraldpickID = config.get(CATEGORY_TOOL, "Emerald Pickaxe", 668).getInt();
		emeraldaxeID = config.get(CATEGORY_TOOL, "Emerald Axe", 669).getInt();
		emeraldshovelID = config.get(CATEGORY_TOOL, "Emerald Shovel", 670).getInt();
		emeraldhoeID = config.get(CATEGORY_TOOL, "Emerald Hoe", 671).getInt();
		emeraldflowerID = config.get(CATEGORY_FLOWER, "Emerald Flower", 672).getInt();
		emeraldhelmetID = config.get(CATEGORY_ARMOR, "Emerald Helmet", 673).getInt();
		emeraldplateID = config.get(CATEGORY_ARMOR, "Emerald Chestplate", 674).getInt();
		emeraldlegsID = config.get(CATEGORY_ARMOR, "Emerald Leggings", 675).getInt();
		emeraldbootsID = config.get(CATEGORY_ARMOR, "Emerald Boots", 676).getInt();
		combinerID = config.get(CATEGORY_ARMOR, "Emerald Boots", 677).getInt();

	}

}
